### ISSUE TITLE
Tube.reserve returns null, but beanstalkd reserves job

### ISSUE THREAD

**Issue by denizzzka** [free-beer/stalkd#4]
beanstalkd 1.10

beanstalkd log:
```
`$ beanstalkd -l 127.0.0.1 -p 11300 -VVV`
[...]
accept 5
<5 command use 
>5 reply USING download_jobs
<5 command put 
<5 job 4
>5 reply INSERTED 4
accept 6
<6 command use 
>6 reply USING download_jobs
<6 command watch 
>6 reply WATCHING 2
<6 command reserve-with-timeout 
>6 reply RESERVED 1 1
>6 job 1
close 6
close 5
```

**Comment by denizzzka** [comment]
Same behviour for `reserve-with-timeout` and `reserve`

**Comment by free-beer** [comment]
Can I just clarify, you're saying that you've made a call to the ```reserve()``` function on a ```Tube``` object and received back a ```null``` response but the server said that a job had actually been reserved? Can you provide steps to reproduce the issue, because it may be difficult to track down the cause otherwise?

**Comment by denizzzka** [comment]
> Can I just clarify, you're saying that you've made a call to the reserve() function on a Tube object and received back a null response but the server said that a job had actually been reserved?

Yes

> Can you provide steps to reproduce the issue, because it may be difficult to track down the cause otherwise?

this is selected lines from our private project

```D
  enum tubeName = "download_jobs";

  private Tube tube() {
    auto tube = new Tube(beantalkdServer);
    tube.use(tubeName);

    return tube;
  }

// append job
{
    auto job = new Job;
    job.append(userId.toString);

    tube.put(job);
}

// retrieve job
{
    auto t = tube;
    t.watch(tubeName);

    auto job = t.reserve(timeOut);

    assert(job !is null);
}
```

**Comment by free-beer** [comment]
Okay, looking at the code, the only thing I can think that might be happening is that the reserve request timed out before the server managed to actually reserve the job and respond. This assumes that your timeout is a positive value of course. This should be the only circumstance in which you get a null response from the ```reserve()``` call, anything else should either return a job or raise an exception. Of course, although the job is reserved now, it will automatically be released once it's time to run has expired, so it hasn't become unreachable. I'm not clear as to whether this is the way that Beanstalkd works though. What kind of value are you using for your timeout?

**Comment by denizzzka** [comment]
2-10 seconds, and also with 0 timeout too

> Same behviour for reserve-with-timeout and reserve

**Comment by free-beer** [comment]
Okay, looking at the protocol definition document (https://github.com/kr/beanstalkd/blob/master/doc/protocol.txt), it's not inconceivable that this may be the way that Beanstalkd works. If you look at the Worker Commands section, it doesn't explicitly state that it will do this but it is kind of implied in text. Behaving in this way does not invalidate the state - the job will not be available immediately and it will become available again later, once it's time to run has expired. Are you setting a TTR for your jobs? The default is 200 seconds, might be worth dropping that if you are processing them quicker.

**Comment by denizzzka** [comment]
> Are you setting a TTR for your jobs?

No

**Comment by free-beer** [comment]
Another question would be, are you seeing this consistently or only occasionally?

**Comment by denizzzka** [comment]
consistently

**Comment by free-beer** [comment]
So every call to ```reserve()``` is returning ```null```? Hmmm, not seeing that happen myself. What platform are you running Beanstalkd on and what platform is the client on? Are they on the same machine?

**Comment by denizzzka** [comment]
this is in integration, I isn't used it in any other cases

> What platform are you running Beanstalkd on

Ubuntu Linux

> and what platform is the client on? Are they on the same machine?

Yes

**Comment by free-beer** [comment]
Hmmm, let me see if I can fire up an Ubuntu instance and try it (I'm working on OSX myself). It will take me a little while though.

**Comment by free-beer** [comment]
Okay, I've compiled this on Ubuntu 17.04 and it works for me...

```d
import std.stdio;
import stalkd;

void main() {
   auto tube = new Tube(Server("127.0.0.1"));
   auto job  = new Job();

   job.append("Content for the job.");

   tube.use("alternative");
   tube.put(job);

   tube.watch("alternative");

   job = null;
   job = tube.reserve(5);
   if(job !is null) {
      writeln("Got '", job.bodyAsString(), "' from reserve().'");
   } else {
      writeln("Got null back from reserve().");
   }
}
```

Am I doing anything substantially different here from what you're doing?

**Comment by denizzzka** [comment]
I am closing tube before open it again and watch

**Comment by free-beer** [comment]
I added the following as lines 13 and 14...

```d
   tube = null;
   tube = new Tube(Server("127.0.0.1"));
```

...and it works. That is effectively creating a completely new ```Tube``` instance with its own connection to the server.

**Comment by denizzzka** [comment]
Found problem: it is because I cast Job to my own inherited from Job class. But I isn't understand why it is happens

**Comment by free-beer** [comment]
Hmmm, well ```reserve()``` builds a Job instance internally and polymorphism works when you cast from a more specific type (i.e. lower down the inheritance hierarchy) to a more general type, higher up the inheritance hierarchy - you'd be doing this in reverse (casting to a more specific type). Not sure why it's causing you issues though. Rather than casting maybe build your more specific Job class around an instance of the stalkd.Job class rather than casting it?

**Comment by denizzzka** [comment]
> Rather than casting maybe build your more specific Job class around an instance of the stalkd.Job class rather than casting it?

Initially, I wanted to save time. :-)

Thank you, sorry for inconvenience!

**Comment by free-beer** [comment]
No problem. Looking at the D documentation for casting it seems that an invalid cast will return ```null``` and while your custom class is derived from the stalkd.Job class, instances of stalkd.Job are technically not instances of (or equivalent to) your custom class so that cast would fail. I think that may be what is going on.

**Comment by denizzzka** [comment]
Yes, I've never faced with upcase before in the D
