### ISSUE TITLE
Proposal: return exception instead of null when timeout occurred

### ISSUE THREAD

**Issue by denizzzka** [free-beer/stalkd#6]
To distinguish timeout from null-valued payload

**Comment by free-beer** [comment]
Not enamoured of that idea. Exceptions are really for 'exceptional' conditions and, in this case, timing out doesn't meet that criteria I think - it is one of the standard possible outcomes. I'll give some consideration to see if I can come up with an alternative way to handle this.

**Comment by denizzzka** [comment]
Another variant: return `Nullable` for `reserve` calls with timeout.

**Comment by free-beer** [comment]
That might be a nicer option alright.

**Comment by free-beer** [comment]
Okay, made a change to the reserve() function, is this what you were thinking?

**Comment by denizzzka** [comment]
Nullable makes sense only for reserve() with timeout argument

**Comment by free-beer** [comment]
True.

**Comment by free-beer** [comment]
I've pushed a version that splits the ```reserve()``` function into two - one blocking one that takes no parameters and a potentially non-blocking one that takes a single integer parameter. The blocking version returns a straight ```Job``` object while the non-blocking one returns a ```Nullable!Job```.
